apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: tech-challenge-group-4
  labels:
    name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: lucasaccurcio/tech-challenge-migration:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: 'postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/tech-challenger'
      restartPolicy: OnFailure
  backoffLimit: 5
