FROM node:20-alpine

WORKDIR /app

# Instala o Prisma CLI globalmente
RUN npm install -g prisma

# Copia apenas os arquivos necessários
COPY package.json package-lock.json ./
COPY prisma ./prisma

# Instala as dependências
RUN npm install

# Expõe a porta padrão do Prisma Studio
EXPOSE 5555

# Comando para iniciar o Prisma Studio
CMD ["npx", "prisma", "studio"]