name: Docker Build and Push for Migrations

on:
  push:
    paths:
      - 'prisma/**'
    branches: ['develop']

jobs:
  docker-migration:
    name: 'Build and Push for Migration'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run install, build, and lint
        run: |
          npm install
          npm run build
          npm run lint

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.migration
          tags: lucasaccurcio/tech-challenge-sso-api:${{ steps.generate_tag.outputs.sha }},lucasaccurcio/tech-challenge-sso-api:latest
